### ISSUE TITLE
Make hardcoded 20 sec timeout to become a parameter

### ISSUE THREAD

**Issue by yarikoptic** [candleindark/cchrome#2]
ATM it is hardcoded to be 20, and (unfortunately) for some use cases might need to be raised higher.

**Comment by candleindark** [comment]
After some consideration, I changed the interface of CChrome completely. In the latest version, the page load  timeout is no longer set in the initialization of CChrome object.

Please note, CChrome now depends on the current versions of selenium and polling2, version 4.5.0 and version 0.5.0 repectively.
